// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: api/user-domain/v1/user-domain.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64    `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name      string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Describe  string   `protobuf:"bytes,5,opt,name=describe,proto3" json:"describe,omitempty"`
	Regions   []uint64 `protobuf:"varint,6,rep,packed,name=regions,proto3" json:"regions,omitempty"`
	Features  []uint64 `protobuf:"varint,7,rep,packed,name=features,proto3" json:"features,omitempty"`
	Users     []uint64 `protobuf:"varint,8,rep,packed,name=users,proto3" json:"users,omitempty"`
}

func (x *Domain) Reset() {
	*x = Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Domain) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Domain) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *Domain) GetRegions() []uint64 {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *Domain) GetFeatures() []uint64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Domain) GetUsers() []uint64 {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateUserDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *CreateUserDomainRequest_Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *CreateUserDomainRequest) Reset() {
	*x = CreateUserDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDomainRequest) ProtoMessage() {}

func (x *CreateUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDomainRequest.ProtoReflect.Descriptor instead.
func (*CreateUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserDomainRequest) GetDomain() *CreateUserDomainRequest_Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type CreateUserDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *CreateUserDomainReply) Reset() {
	*x = CreateUserDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDomainReply) ProtoMessage() {}

func (x *CreateUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDomainReply.ProtoReflect.Descriptor instead.
func (*CreateUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserDomainReply) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type UpdateUserDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *UpdateUserDomainRequest_Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *UpdateUserDomainRequest) Reset() {
	*x = UpdateUserDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDomainRequest) ProtoMessage() {}

func (x *UpdateUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDomainRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserDomainRequest) GetDomain() *UpdateUserDomainRequest_Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type UpdateUserDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *UpdateUserDomainReply) Reset() {
	*x = UpdateUserDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDomainReply) ProtoMessage() {}

func (x *UpdateUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDomainReply.ProtoReflect.Descriptor instead.
func (*UpdateUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserDomainReply) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type DeleteUserDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserDomainRequest) Reset() {
	*x = DeleteUserDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDomainRequest) ProtoMessage() {}

func (x *DeleteUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDomainRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserDomainRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *DeleteUserDomainReply) Reset() {
	*x = DeleteUserDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDomainReply) ProtoMessage() {}

func (x *DeleteUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDomainReply.ProtoReflect.Descriptor instead.
func (*DeleteUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserDomainReply) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type GetUserDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserDomainRequest) Reset() {
	*x = GetUserDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDomainRequest) ProtoMessage() {}

func (x *GetUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDomainRequest.ProtoReflect.Descriptor instead.
func (*GetUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserDomainRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *GetUserDomainReply) Reset() {
	*x = GetUserDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDomainReply) ProtoMessage() {}

func (x *GetUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDomainReply.ProtoReflect.Descriptor instead.
func (*GetUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserDomainReply) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type FindUserDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index int64  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FindUserDomainRequest) Reset() {
	*x = FindUserDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserDomainRequest) ProtoMessage() {}

func (x *FindUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserDomainRequest.ProtoReflect.Descriptor instead.
func (*FindUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{9}
}

func (x *FindUserDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindUserDomainRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FindUserDomainRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FindUserDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   int64     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size    int64     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Page    int64     `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total   int64     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Domains []*Domain `protobuf:"bytes,5,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *FindUserDomainReply) Reset() {
	*x = FindUserDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserDomainReply) ProtoMessage() {}

func (x *FindUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserDomainReply.ProtoReflect.Descriptor instead.
func (*FindUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{10}
}

func (x *FindUserDomainReply) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FindUserDomainReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FindUserDomainReply) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindUserDomainReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FindUserDomainReply) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListUserDomainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListUserDomainRequest) Reset() {
	*x = ListUserDomainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainRequest) ProtoMessage() {}

func (x *ListUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainRequest.ProtoReflect.Descriptor instead.
func (*ListUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{11}
}

type ListUserDomainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domains []*Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *ListUserDomainReply) Reset() {
	*x = ListUserDomainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainReply) ProtoMessage() {}

func (x *ListUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainReply.ProtoReflect.Descriptor instead.
func (*ListUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserDomainReply) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type CreateUserDomainRequest_Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Describe string   `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	Regions  []uint64 `protobuf:"varint,3,rep,packed,name=regions,proto3" json:"regions,omitempty"`
	Features []uint64 `protobuf:"varint,4,rep,packed,name=features,proto3" json:"features,omitempty"`
	Users    []uint64 `protobuf:"varint,5,rep,packed,name=users,proto3" json:"users,omitempty"`
}

func (x *CreateUserDomainRequest_Domain) Reset() {
	*x = CreateUserDomainRequest_Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserDomainRequest_Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDomainRequest_Domain) ProtoMessage() {}

func (x *CreateUserDomainRequest_Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDomainRequest_Domain.ProtoReflect.Descriptor instead.
func (*CreateUserDomainRequest_Domain) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateUserDomainRequest_Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserDomainRequest_Domain) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *CreateUserDomainRequest_Domain) GetRegions() []uint64 {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *CreateUserDomainRequest_Domain) GetFeatures() []uint64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *CreateUserDomainRequest_Domain) GetUsers() []uint64 {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserDomainRequest_Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Describe string   `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	Regions  []uint64 `protobuf:"varint,4,rep,packed,name=regions,proto3" json:"regions,omitempty"`
	Features []uint64 `protobuf:"varint,5,rep,packed,name=features,proto3" json:"features,omitempty"`
	Users    []uint64 `protobuf:"varint,6,rep,packed,name=users,proto3" json:"users,omitempty"`
}

func (x *UpdateUserDomainRequest_Domain) Reset() {
	*x = UpdateUserDomainRequest_Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserDomainRequest_Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDomainRequest_Domain) ProtoMessage() {}

func (x *UpdateUserDomainRequest_Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_domain_v1_user_domain_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDomainRequest_Domain.ProtoReflect.Descriptor instead.
func (*UpdateUserDomainRequest_Domain) Descriptor() ([]byte, []int) {
	return file_api_user_domain_v1_user_domain_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateUserDomainRequest_Domain) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserDomainRequest_Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserDomainRequest_Domain) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *UpdateUserDomainRequest_Domain) GetRegions() []uint64 {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *UpdateUserDomainRequest_Domain) GetFeatures() []uint64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *UpdateUserDomainRequest_Domain) GetUsers() []uint64 {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_api_user_domain_v1_user_domain_proto protoreflect.FileDescriptor

var file_api_user_domain_v1_user_domain_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0xeb, 0x01, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x1a, 0x84, 0x01, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x4a, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xfb, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x49, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x94, 0x01,
	0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x22, 0x4a, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x47, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x55, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x9e, 0x01, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x33, 0x0a, 0x07, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73,
	0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x13, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x33, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x07, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x73, 0x32, 0xbc, 0x06, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x8b, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x8b, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x8b, 0x01, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1b, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x7f,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x67, 0x65, 0x74, 0x12,
	0x83, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x17, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2f, 0x66, 0x69, 0x6e, 0x64, 0x12, 0x7d, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x6c, 0x69, 0x73, 0x74, 0x42, 0x39, 0x0a, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x21, 0x75, 0x73,
	0x65, 0x72, 0x2d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_user_domain_v1_user_domain_proto_rawDescOnce sync.Once
	file_api_user_domain_v1_user_domain_proto_rawDescData = file_api_user_domain_v1_user_domain_proto_rawDesc
)

func file_api_user_domain_v1_user_domain_proto_rawDescGZIP() []byte {
	file_api_user_domain_v1_user_domain_proto_rawDescOnce.Do(func() {
		file_api_user_domain_v1_user_domain_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_domain_v1_user_domain_proto_rawDescData)
	})
	return file_api_user_domain_v1_user_domain_proto_rawDescData
}

var file_api_user_domain_v1_user_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_user_domain_v1_user_domain_proto_goTypes = []interface{}{
	(*Domain)(nil),                         // 0: api.userdomain.v1.Domain
	(*CreateUserDomainRequest)(nil),        // 1: api.userdomain.v1.CreateUserDomainRequest
	(*CreateUserDomainReply)(nil),          // 2: api.userdomain.v1.CreateUserDomainReply
	(*UpdateUserDomainRequest)(nil),        // 3: api.userdomain.v1.UpdateUserDomainRequest
	(*UpdateUserDomainReply)(nil),          // 4: api.userdomain.v1.UpdateUserDomainReply
	(*DeleteUserDomainRequest)(nil),        // 5: api.userdomain.v1.DeleteUserDomainRequest
	(*DeleteUserDomainReply)(nil),          // 6: api.userdomain.v1.DeleteUserDomainReply
	(*GetUserDomainRequest)(nil),           // 7: api.userdomain.v1.GetUserDomainRequest
	(*GetUserDomainReply)(nil),             // 8: api.userdomain.v1.GetUserDomainReply
	(*FindUserDomainRequest)(nil),          // 9: api.userdomain.v1.FindUserDomainRequest
	(*FindUserDomainReply)(nil),            // 10: api.userdomain.v1.FindUserDomainReply
	(*ListUserDomainRequest)(nil),          // 11: api.userdomain.v1.ListUserDomainRequest
	(*ListUserDomainReply)(nil),            // 12: api.userdomain.v1.ListUserDomainReply
	(*CreateUserDomainRequest_Domain)(nil), // 13: api.userdomain.v1.CreateUserDomainRequest.Domain
	(*UpdateUserDomainRequest_Domain)(nil), // 14: api.userdomain.v1.UpdateUserDomainRequest.Domain
}
var file_api_user_domain_v1_user_domain_proto_depIdxs = []int32{
	13, // 0: api.userdomain.v1.CreateUserDomainRequest.domain:type_name -> api.userdomain.v1.CreateUserDomainRequest.Domain
	0,  // 1: api.userdomain.v1.CreateUserDomainReply.domain:type_name -> api.userdomain.v1.Domain
	14, // 2: api.userdomain.v1.UpdateUserDomainRequest.domain:type_name -> api.userdomain.v1.UpdateUserDomainRequest.Domain
	0,  // 3: api.userdomain.v1.UpdateUserDomainReply.domain:type_name -> api.userdomain.v1.Domain
	0,  // 4: api.userdomain.v1.DeleteUserDomainReply.domain:type_name -> api.userdomain.v1.Domain
	0,  // 5: api.userdomain.v1.GetUserDomainReply.domain:type_name -> api.userdomain.v1.Domain
	0,  // 6: api.userdomain.v1.FindUserDomainReply.domains:type_name -> api.userdomain.v1.Domain
	0,  // 7: api.userdomain.v1.ListUserDomainReply.domains:type_name -> api.userdomain.v1.Domain
	1,  // 8: api.userdomain.v1.UserDomain.CreateUserDomain:input_type -> api.userdomain.v1.CreateUserDomainRequest
	3,  // 9: api.userdomain.v1.UserDomain.UpdateUserDomain:input_type -> api.userdomain.v1.UpdateUserDomainRequest
	5,  // 10: api.userdomain.v1.UserDomain.DeleteUserDomain:input_type -> api.userdomain.v1.DeleteUserDomainRequest
	7,  // 11: api.userdomain.v1.UserDomain.GetUserDomain:input_type -> api.userdomain.v1.GetUserDomainRequest
	9,  // 12: api.userdomain.v1.UserDomain.FindUserDomain:input_type -> api.userdomain.v1.FindUserDomainRequest
	11, // 13: api.userdomain.v1.UserDomain.ListUserDomain:input_type -> api.userdomain.v1.ListUserDomainRequest
	2,  // 14: api.userdomain.v1.UserDomain.CreateUserDomain:output_type -> api.userdomain.v1.CreateUserDomainReply
	4,  // 15: api.userdomain.v1.UserDomain.UpdateUserDomain:output_type -> api.userdomain.v1.UpdateUserDomainReply
	6,  // 16: api.userdomain.v1.UserDomain.DeleteUserDomain:output_type -> api.userdomain.v1.DeleteUserDomainReply
	8,  // 17: api.userdomain.v1.UserDomain.GetUserDomain:output_type -> api.userdomain.v1.GetUserDomainReply
	10, // 18: api.userdomain.v1.UserDomain.FindUserDomain:output_type -> api.userdomain.v1.FindUserDomainReply
	12, // 19: api.userdomain.v1.UserDomain.ListUserDomain:output_type -> api.userdomain.v1.ListUserDomainReply
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_user_domain_v1_user_domain_proto_init() }
func file_api_user_domain_v1_user_domain_proto_init() {
	if File_api_user_domain_v1_user_domain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_domain_v1_user_domain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserDomainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserDomainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserDomainRequest_Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_domain_v1_user_domain_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserDomainRequest_Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_domain_v1_user_domain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_domain_v1_user_domain_proto_goTypes,
		DependencyIndexes: file_api_user_domain_v1_user_domain_proto_depIdxs,
		MessageInfos:      file_api_user_domain_v1_user_domain_proto_msgTypes,
	}.Build()
	File_api_user_domain_v1_user_domain_proto = out.File
	file_api_user_domain_v1_user_domain_proto_rawDesc = nil
	file_api_user_domain_v1_user_domain_proto_goTypes = nil
	file_api_user_domain_v1_user_domain_proto_depIdxs = nil
}
